---
deployment:
  tasks:
    # Set the path where the app should be deployed (e.g., public_html)
    - export DEPLOYPATH=/home/mannatem/treda_test/.cpanel.yml
    # Copy files/folders from the Git repo root to the deployment path
    - /bin/cp -R * $DEPLOYPATH